import type { Seller, Product } from './types';

export const allSellers: Seller[] = [
  {
    id: 'seller-1',
    name: 'Alice',
    avatarUrl: 'https://i.pravatar.cc/150?u=alice',
    trustScore: 92,
    ratings: 45,
    location: 'Elm Street',
    locationRank: 1,
  },
  {
    id: 'seller-2',
    name: 'Bob',
    avatarUrl: 'https://i.pravatar.cc/150?u=bob',
    trustScore: 88,
    ratings: 32,
    location: 'Oak Apartments',
    locationRank: 2,
  },
  {
    id: 'seller-3',
    name: 'Charlie',
    avatarUrl: 'https://i.pravatar.cc/150?u=charlie',
    trustScore: 98,
    ratings: 102,
    location: 'Maple Court',
    locationRank: 3,
  },
  {
    id: 'seller-4',
    name: 'Diana',
    avatarUrl: 'https://i.pravatar.cc/150?u=diana',
    trustScore: 75,
    ratings: 15,
    location: 'Elm Street',
    locationRank: 1,
  },
];

export const allProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'High-Speed Blender',
    description:
      'Gently used high-speed blender, perfect for smoothies and soups. Comes with all original accessories and packaging. Selling because I upgraded to a new model.',
    price: 45.0,
    category: 'Household',
    imageUrl: 'https://picsum.photos/seed/blender/600/400',
    imageHint: 'kitchen appliance',
    images: [
      { id: '1', url: 'https://picsum.photos/seed/blender/600/400', hint: 'kitchen appliance' },
      { id: '2', url: 'https://picsum.photos/seed/blender-2/600/400', hint: 'kitchen appliance action' },
      { id: '3', url: 'https://picsum.photos/seed/blender-3/600/400', hint: 'kitchen appliance parts' },
    ],
    sellerId: 'seller-1',
    postedDate: '2024-07-22T10:00:00Z',
    reviews: [
      {
        id: 'rev-1',
        author: 'Frank',
        avatarUrl: 'https://i.pravatar.cc/150?u=frank',
        rating: 5,
        comment: 'Great condition and works perfectly!',
      },
    ],
    priceComparisons: [
      { store: 'Retail', price: 120.0 },
      { store: 'Amazon', price: 99.0 },
    ],
  },
  {
    id: 'prod-2',
    name: 'Noise-Cancelling Headphones',
    description:
      'Almost new wireless headphones with amazing noise cancellation. Used only a few times. Battery life is excellent. Includes charging cable and case.',
    price: 80.0,
    category: 'Electronics',
    imageUrl: 'https://picsum.photos/seed/headphones/600/400',
    imageHint: 'tech gadget',
    images: [{ id: '1', url: 'https://picsum.photos/seed/headphones/600/400', hint: 'tech gadget' }],
    sellerId: 'seller-2',
    postedDate: '2024-07-21T14:30:00Z',
    reviews: [],
    priceComparisons: [
      { store: 'Best Buy', price: 199.99 },
      { store: 'Online Store', price: 179.5 },
    ],
  },
  {
    id: 'prod-3',
    name: 'Monstera Deliciosa Plant',
    description:
      'Beautiful, healthy Monstera plant in a ceramic pot. It has outgrown my space. Needs a new loving home with bright, indirect light.',
    price: 25.0,
    category: 'Garden',
    imageUrl: 'https://picsum.photos/seed/plant/600/400',
    imageHint: 'house plant',
    images: [{ id: '1', url: 'https://picsum.photos/seed/plant/600/400', hint: 'house plant' }],
    sellerId: 'seller-3',
    postedDate: '2024-07-22T11:00:00Z',
    reviews: [
      {
        id: 'rev-2',
        author: 'Grace',
        avatarUrl: 'https://i.pravatar.cc/150?u=grace',
        rating: 5,
        comment: 'Gorgeous plant, and Charlie was super helpful with care tips!',
      },
      {
        id: 'rev-3',
        author: 'Heidi',
        avatarUrl: 'https://i.pravatar.cc/150?u=heidi',
        rating: 4,
        comment: 'Very healthy plant, a bit smaller than expected but still lovely.',
      },
    ],
    priceComparisons: [{ store: 'Nursery', price: 50.0 }],
  },
  {
    id: 'prod-4',
    name: 'Organic Garden Tomatoes',
    description:
      'Homegrown, organic tomatoes. Super sweet and juicy. Selling by the pound. Perfect for salads, sauces, or just eating fresh.',
    price: 3.5,
    category: 'Food',
    imageUrl: 'https://picsum.photos/seed/tomatoes/600/400',
    imageHint: 'fresh vegetables',
    images: [{ id: '1', url: 'https://picsum.photos/seed/tomatoes/600/400', hint: 'fresh vegetables' }],
    sellerId: 'seller-1',
    postedDate: '2024-07-23T09:00:00Z',
    reviews: [],
    priceComparisons: [{ store: 'Farmers Market', price: 5.0 }],
  },
  {
    id: 'prod-5',
    name: 'Vintage Road Bike',
    description:
      'Classic 10-speed road bike. In good condition, just needs a little tune-up. Great for cruising around the neighborhood.',
    price: 120.0,
    category: 'Other',
    imageUrl: 'https://picsum.photos/seed/bike/600/400',
    imageHint: 'bicycle',
    images: [{ id: '1', url: 'https://picsum.photos/seed/bike/600/400', hint: 'bicycle' }],
    sellerId: 'seller-4',
    postedDate: '2024-07-20T18:00:00Z',
    reviews: [],
    priceComparisons: [],
  },
  {
    id: 'prod-6',
    name: 'Mechanical Keyboard',
    description: 'Clicky mechanical keyboard with RGB backlighting. Great for gaming or typing. Cleaned and fully functional.',
    price: 60,
    category: 'Electronics',
    imageUrl: 'https://picsum.photos/seed/keyboard/600/400',
    imageHint: 'computer keyboard',
    images: [
      { id: '1', url: 'https://picsum.photos/seed/keyboard/600/400', hint: 'computer keyboard' },
      { id: '2', url: 'https://picsum.photos/seed/keyboard-2/600/400', hint: 'computer keyboard light' },
    ],
    sellerId: 'seller-2',
    postedDate: '2024-07-22T19:00:00Z',
    reviews: [
      {
        id: 'rev-4',
        author: 'Ivan',
        avatarUrl: 'https://i.pravatar.cc/150?u=ivan',
        rating: 5,
        comment: 'As described, great keyboard!',
      },
    ],
    priceComparisons: [{ store: 'Retail', price: 130 }],
  },
  {
    id: 'prod-7',
    name: 'Art Deco Desk Lamp',
    description: 'Stylish Art Deco lamp, gives off a warm light. Perfect for a desk or side table. Selling as I redecorated.',
    price: 30,
    category: 'Household',
    imageUrl: 'https://picsum.photos/seed/lamp/600/400',
    imageHint: 'desk lamp',
    images: [{ id: '1', url: 'https://picsum.photos/seed/lamp/600/400', hint: 'desk lamp' }],
    sellerId: 'seller-3',
    postedDate: '2024-07-23T12:00:00Z',
    reviews: [],
    priceComparisons: [],
  },
  {
    id: 'prod-8',
    name: 'Fresh Cucumbers',
    description: 'Crisp and delicious cucumbers from my garden. No pesticides used. Price is per cucumber.',
    price: 1,
    category: 'Food',
    imageUrl: 'https://picsum.photos/seed/cucumber/600/400',
    imageHint: 'fresh vegetables',
    images: [{ id: '1', url: 'https://picsum.photos/seed/cucumber/600/400', hint: 'fresh vegetables' }],
    sellerId: 'seller-1',
    postedDate: '2024-07-23T09:05:00Z',
    reviews: [],
    priceComparisons: [{ store: 'Grocery Store', price: 1.5 }],
  },
];
